### PR TITLE
upgrade test cert for Nexus

### PR DESCRIPTION
**Pull request by LindaLawtonDk**

### CODE REVIEW

**Comment by ohetrifork** [comment]
Hi @LindaLawtonDk 
Do you have any wishes for deployment time? We usually take changes to "PreCAB meetings" on Tuesdays (too late for today, though), and can proceed with deployments the following Thursday.

**Comment by ohetrifork** [comment]
Hi @LindaLawtonDk 
I don't think we require you to use production keys on the test environment. That hasn't been the case for any other client systems. There is no technical issue adding your production key to the test environment, but it might be because you have supplied your production key to the Serviceplatform exttest environment? We only accept tokens from the exttest STS on our test environment.
Please confirm, if you still want your production key added to our test environment

**Comment by LindaLawton** [comment]
Apparently there may have been some miss communication.

A test certificate was created for us that we can't use.    So we decided to try with the production certificate.   Thinking that's what they meant.

Hold of while we have a new production certificate create that can be registered in kombit and then added as A new test certificate here.

At least I think that's what we are doing,  still going through several people before it gets too me.   🤞


Linda

**Comment by LindaLawtonDk** [comment]
This should be "a production cert"  but not "the production cert".  For test.  Kombit is down so we have not added it to their system.

**Comment by ohetrifork** [comment]
I'll arrange a service window for doing the update

**Comment by ohetrifork** [comment]
I have a window from 13-14 today for doing the update. I'll write here once it's done

**Comment by LindaLawtonDk** [comment]
thank you so much for getting this pushed though for us.

**Comment by ohetrifork** [comment]
New public key is now active on the test environment

**Comment by LindaLawtonDk** [comment]
unfortunately its still not working we cant contact test.  Does this error message mean anything to you?

[13:11:21 WRN] Access token request failed {"error":"invalid_client","error_description":"Unable to load public key"}
[13:11:21 WRN] Failed to request access token 361000016006:67284DA7-F14C-4A97-862D-9B281DFB0538 report not sent {"error":"invalid_client","error_description":"Unable to load public key"}

**Comment by ohetrifork** [comment]
@nigtrifork do you know the reason behind the error above?

**Comment by ohetrifork** [comment]
Damn... this one's on me. I changed the wrong key. Service window is still open. I'll give it a new go

**Comment by LindaLawtonDk** [comment]
I was thinking maybe we forgot to add it to someplace :/

**Comment by ohetrifork** [comment]
The right key has been updated now - please give it a new try.

**Comment by LindaLawtonDk** [comment]
thank you thank you thank you its working

**Pull request merged**
