### PR TITLE
[(CuraDevelopment)] Updated pem files for coumna_cura

### PR DESCRIPTION
**Pull request by CuraDevelopment**

### CODE REVIEW

**Comment by CuraDevelopment** [comment]
Updated pem files for coumna_cura to klgateway.

**Comment by ohetrifork** [comment]
I will see what I can do. Notice that this will cause existing certificates to be blacklisted.

**Comment by ohetrifork** [comment]
I have created a change task to be handled on a PreCAB meeting tomorrow, Tuesday 24/10. I have suggested the change to be carried out on Thursday 26/10 9-10. I will report on status after that meeting.
Notice, that once this change has been implemented, the previous certificates can no longer be used.

**Comment by ohetrifork** [comment]
@CuraDevelopment the deployment will most likely be scheduled for 13-14 on Thursday. Will you be able to verify after deployment, or will you wait to see the result of the following night's transfers?

**Comment by CuraDevelopment** [comment]
We won't be able to see it until nighttime. We expect that it will fail for some customers until they've had the certificate changed - the synchronization task should automatically resume.

**Comment by ohetrifork** [comment]
FYI: The change windows has been moved to 14-15 on Thursday 26/10

**Comment by ohetrifork** [comment]
@CuraDevelopment : The new public keys are now active. I will look into status tomorrow wrt. Cura transfers

**Comment by ohetrifork** [comment]
@CuraDevelopment we don't see any successful ingest from Cura clients this morning. Can you confirm that the certificates have not been changed on your side?

**Comment by CuraDevelopment** [comment]
Aalbertslund should be on the new certificate.. but 10 more customers are added today.

**Comment by ohetrifork** [comment]
FYI @CuraDevelopment: we have not seen data from any of your municipalities over the weekend.

**Comment by ohetrifork** [comment]
@CuraDevelopment: We are seeing thousands of your calls being rejected on a daily basis, and the number increases every day. Any updates from you on this issue?

**Comment by CuraDevelopment** [comment]
@ohetrifork a hotfix is delivered today, hopefully that will solve the issue for most of the customers.

**Comment by ohetrifork** [comment]
Great, I see traffic from 11 of your municipalities this morning:
image

**Pull request merged**
