### PR TITLE
[(main)] update public key for client: systematic-columna-cura-test

### PR DESCRIPTION
**Pull request by aonsystematic**
update public key for client id: `systematic-columna-cura-test`

### CODE REVIEW

**Comment by ohetrifork** [comment]
I have asked the change board for a service window to update the public key. I'll return with more information when it reaches me.

**Comment by aonsystematic** [comment]
can I get a status on this?

**Comment by ohetrifork** [comment]
The issue is still at the change board (https://support.systematic.com/browse/FUT1-9272). I have asked for a status update

**Comment by ohetrifork** [comment]
The new public key will be updated this afternoon. I will update this case when the change has been completed

**Comment by ohetrifork** [comment]
The change has now been completed

**Pull request merged**
